version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    restart: unless-stopped
    user: root
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - localstack-net
    environment:
      - DYNAMO_TABLE=${DYNAMO_TABLE}

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: nsee
      MINIO_ROOT_PASSWORD: nsee
      BUCKET_NAME: ${BUCKET_NAME}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - localstack-net

  init:
    image: python:3.11
    container_name: aws_local_init
    depends_on:
      - dynamodb-local
      - minio
    volumes:
      - ./init:/app
    working_dir: /app
    command: [ "sh", "init.sh" ]
    networks:
      - localstack-net
    environment:
      DYNAMO_TABLE: ${DYNAMO_TABLE}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio

volumes:
  dynamodb_data:
  minio_data:

networks:
  localstack-net:
    driver: bridge
