version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/data/
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    networks:
      - local-aws-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: nseeadmin
      MINIO_ROOT_PASSWORD: nseeadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - local-aws-net

  setup-script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setup-script
    depends_on:
      dynamodb-local:
        condition: service_started
      minio:
        condition: service_healthy
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-meu-bucket-local-compose}
      - DYNAMO_TABLE=${DYNAMO_TABLE:-minha-tabela-local-compose}
      - AWS_ACCESS_KEY_ID=nseeadmin
      - AWS_SECRET_ACCESS_KEY=nseeadmin
      - AWS_DEFAULT_REGION=us-east-1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - local-aws-net

networks:
  local-aws-net:
    driver: bridge